id: I998BE685
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:44:59+00:00'
last_modified: '2022-06-07T21:20:31.165487+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22026
  title: 'མི་ཉག་མཁས་དབང་ལྔའི་རྣམ་ཐར་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BBBA:
      image_group_id: I1PD28137
      title: ''
      total_pages: 226
      order: 1
      base_file: BBBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
