id: P004241
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:04:00.725630
source_metadata:
  id: bdr:W22026
  title: 'མི་ཉག་མཁས་དབང་ལྔའི་རྣམ་ཐར་། '
  author: ''
  volumes:
    d525d8915e7e4a9b88fdd1a68233c54c:
      image_group_id: I1PD28137
      title: ''
      volume_number: 1
      total_pages: 226
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
